name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'   # Trigger hanya jika ada push tag sesuai semver, misal v1.0.0, v1.2.3, dst.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'      # Atau versi Node yang diinginkan
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      # Jika menggunakan TypeScript, tambahkan build step:
      # - name: Build
      #   run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
