name: Publish Package

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # === Setup untuk publish ke npmjs.org ===
      - name: Setup Node.js for npmjs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@galihru'        # scope package-mu

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build       # atau npm run sesuai script-mu

      - name: Publish to npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  
        run: npm publish --access public

      # === Buat status deployment untuk npmjs.org (opsional) ===
      - name: Create deployment status
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              environment: 'npmjs',
              description: `Published @galihru/pqlaicrypto@${require('./package.json').version}`,
              auto_merge: false,
              required_contexts: []
            });
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: 'success',
              environment_url: `https://www.npmjs.com/package/@galihru/pqlaicrypto`,
              log_url: `https://www.npmjs.com/package/@galihru/pqlaicrypto`,
              description: `Version ${require('./package.json').version} published to npmjs`
            });

      # === Setup untuk publish ke GitHub Packages ===
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@galihru'

      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Adjust package.json for GitHub Packages
        run: |
          # backup
          cp package.json package.json.bak
          # ubah name & publishConfig
          jq '.name = "@galihru/pqlaicrypto" 
              | .publishConfig = { "registry": "https://npm.pkg.github.com" }' \
              package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Publish to GitHub Packages
        run: npm publish --access public

      - name: Restore original package.json
        run: mv package.json.bak package.json
