name: Build and Publish Gem to RubyGems

on:
  push:
    branches: [ main ]
    tags: ['v*.*.*']

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Setup Ruby environment
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      # 3) Build gem file (.gem)
      - name: Build gem
        run: gem build laicrypto.gemspec

      # 4) Konfigurasi ~/.gem/credentials agar bisa push ke GH Packages
      - name: Configure RubyGems credentials for GitHub Packages
        run: |
          mkdir -p ~/.gem
          echo -n "---\n" > ~/.gem/credentials
          echo -n "https://rubygems.pkg.github.com/4211421036: $GHCR_API_KEY\n" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
        env:
          # Ambil secret PAT yang kita simpan sebagai GHCR_API_KEY
          GHCR_API_KEY: ${{ secrets.GHCR_API_KEY }}

      # 5) Push gem ke GitHub Packages (tidak perlu --api-key karena credentials sudah di ~/.gem/credentials)
      - name: Build Gem
        run: |
          gem build laicrypto.gemspec
          ls -la  # Verifikasi apakah file .gem sudah ada
      
      - name: Push to GitHub Packages
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
        run: |
          mkdir -p ~/.gem
          echo -e "---\n:github: $GEM_HOST_API_KEY" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem push --key github --host https://rubygems.pkg.github.com/4211421036 g4lihru-laicrypto-0.1.0.gem
