name: Publish & Create Deployment

on:
  push:
    branches: 
      - main

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}

      - name: Cache Cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.toml') }}

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --quiet

      - name: Create GitHub Deployment
        id: create_deploy
        uses: actions/create-deployment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: crates.io
          transient_environment: false
          production_environment: true
          description: 'Published version ${{ github.ref_name }} to crates.io'

      - name: Set Deployment Status
        uses: actions/deployment-status@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.create_deploy.outputs.deployment_id }}
          state: success
          environment_url: https://crates.io/crates/laicrypto
